trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: ls -R
  displayName: "Check Structure"

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'   # change if inside folder
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
