# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
      versionspe : '3.10'
      displayName : "Use  Python 3.10"
- scripts: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       displayName: "Install  Dependencies"
-script: |
        python train.py
        displayName: "run automated model training"
-script: | 
        ls -R
        displayName: "repo structure"
        
