trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: "Use Python"

# Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
  displayName: "Install Dependencies"

# Debug (optional but useful)
- script: |
    ls -R
  displayName: "Check Repo Structure"

# Run tests
- script: |
    pytest test.py
  displayName: "Run Tests"

# Run training
- script: |
    python train.py
  displayName: "Run Training"
