services:
  - type: web
    name: wheat-disease-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ENVIRONMENT
        value: production
